<!-- ckeditor -->
{{HTML::script("ckeditor/adapters/jquery.js")}}

{{HTML::script("ckeditor/lang/af.js")}}
{{HTML::script("ckeditor/lang/ar.js")}}
{{HTML::script("ckeditor/lang/bg.js")}}
{{HTML::script("ckeditor/lang/bn.js")}}
{{HTML::script("ckeditor/lang/bs.js")}}
{{HTML::script("ckeditor/lang/ca.js")}}
{{HTML::script("ckeditor/lang/cs.js")}}
{{HTML::script("ckeditor/lang/cy.js")}}
{{HTML::script("ckeditor/lang/da.js")}}
{{HTML::script("ckeditor/lang/de.js")}}
{{HTML::script("ckeditor/lang/el.js")}}
{{HTML::script("ckeditor/lang/en.js")}}
{{HTML::script("ckeditor/lang/en-au.js")}}
{{HTML::script("ckeditor/lang/en-ca.js")}}
{{HTML::script("ckeditor/lang/en-gb.js")}}
{{HTML::script("ckeditor/lang/eo.js")}}
{{HTML::script("ckeditor/lang/es.js")}}
{{HTML::script("ckeditor/lang/et.js")}}
{{HTML::script("ckeditor/lang/eu.js")}}
{{HTML::script("ckeditor/lang/fa.js")}}
{{HTML::script("ckeditor/lang/fi.js")}}
{{HTML::script("ckeditor/lang/fo.js")}}
{{HTML::script("ckeditor/lang/fr.js")}}
{{HTML::script("ckeditor/lang/fr-ca.js")}}
{{HTML::script("ckeditor/lang/gl.js")}}
{{HTML::script("ckeditor/lang/gu.js")}}
{{HTML::script("ckeditor/lang/he.js")}}
{{HTML::script("ckeditor/lang/hi.js")}}
{{HTML::script("ckeditor/lang/hr.js")}}
{{HTML::script("ckeditor/lang/hu.js")}}
{{HTML::script("ckeditor/lang/id.js")}}
{{HTML::script("ckeditor/lang/is.js")}}
{{HTML::script("ckeditor/lang/it.js")}}
{{HTML::script("ckeditor/lang/ja.js")}}
{{HTML::script("ckeditor/lang/ka.js")}}
{{HTML::script("ckeditor/lang/km.js")}}
{{HTML::script("ckeditor/lang/ko.js")}}
{{HTML::script("ckeditor/lang/ku.js")}}
{{HTML::script("ckeditor/lang/lt.js")}}
{{HTML::script("ckeditor/lang/lv.js")}}
{{HTML::script("ckeditor/lang/mk.js")}}
{{HTML::script("ckeditor/lang/mn.js")}}
{{HTML::script("ckeditor/lang/ms.js")}}
{{HTML::script("ckeditor/lang/nb.js")}}
{{HTML::script("ckeditor/lang/nl.js")}}
{{HTML::script("ckeditor/lang/no.js")}}
{{HTML::script("ckeditor/lang/pl.js")}}
{{HTML::script("ckeditor/lang/pt.js")}}
{{HTML::script("ckeditor/lang/pt-br.js")}}
{{HTML::script("ckeditor/lang/ro.js")}}
{{HTML::script("ckeditor/lang/ru.js")}}
{{HTML::script("ckeditor/lang/si.js")}}
{{HTML::script("ckeditor/lang/sk.js")}}
{{HTML::script("ckeditor/lang/sl.js")}}
{{HTML::script("ckeditor/lang/sq.js")}}
{{HTML::script("ckeditor/lang/sr.js")}}
{{HTML::script("ckeditor/lang/sr-latin.js")}}
{{HTML::script("ckeditor/lang/sv.js")}}
{{HTML::script("ckeditor/lang/th.js")}}
{{HTML::script("ckeditor/lang/tr.js")}}
{{HTML::script("ckeditor/lang/tt.js")}}
{{HTML::script("ckeditor/lang/ug.js")}}
{{HTML::script("ckeditor/lang/uk.js")}}
{{HTML::script("ckeditor/lang/vi.js")}}
{{HTML::script("ckeditor/lang/zh.js")}}
{{HTML::script("ckeditor/lang/zh-cn.js")}}


<!-- Css CKeditor -->
{{HTML::style("ckeditor/content.css")}}
{{HTML::style("ckeditor/skins/moono/dialog.css")}}
{{HTML::style("ckeditor/skins/moono/dialog_ie.css")}}
{{HTML::style("ckeditor/skins/moono/dialog_ie7.css")}}
{{HTML::style("ckeditor/skins/moono/dialog_ie8.css")}}
{{HTML::style("ckeditor/skins/moono/dialog_iequirks.css")}}
{{HTML::style("ckeditor/skins/moono/editor.css")}}
{{HTML::style("ckeditor/skins/moono/editor_ie.css")}}
{{HTML::style("ckeditor/skins/moono/editor_ie7.css")}}
{{HTML::style("ckeditor/skins/moono/editor_ie8.css")}}
{{HTML::style("ckeditor/skins/moono/editor_iequirks.css")}}
{{HTML::style("ckeditor/samples/sample.css")}}
{{HTML::style("ckeditor/samples/assest/outputxhtml/outputxhtml.css")}}
{{HTML::style("ckeditor/plugins/wsc/dialogs/wsc.css")}}

<!-- Js CKeditor-->
{{HTML::script("ckeditor/samples/sample.js")}}
{{HTML::script("ckeditor/samples/assets/uilanguages/languages.js")}}
{{HTML::script("ckeditor/samples/plugins/dialog/assets/my_dialog.js")}}
{{HTML::script("ckeditor/samples/plugins/htmlwriter/assets/outputforflash/swfobject.js")}}
{{HTML::script("ckeditor/build-config.js")}}
{{HTML::script("ckeditor/ckeditor.js")}}
{{HTML::script("ckeditor/config.js")}}
{{HTML::script("ckeditor/style.js")}}

{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/a11yhelp.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/af.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ar.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/bg.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ca.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/cs.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/cy.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/da.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/de.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/el.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/en.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/en-gb.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/eo.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/es.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/et.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/fa.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/fi.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/fr.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/fr-ca.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/gl.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/gu.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/he.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/hi.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/hr.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/hu.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/id.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/it.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ja.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/km.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ko.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ku.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/lt.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/lv.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/mk.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/mn.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/nb.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/nl.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/no.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/pl.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/pt.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/pt-br.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ro.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ru.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/si.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sk.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sl.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sq.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sr.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sr-latn.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/sv.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/th.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/tr.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/tt.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/ug.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/uk.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/vi.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/zh.js")}}
{{HTML::script("ckeditor/plugins/a11yhelp/dialogs/lang/zh-cn.js")}}
{{HTML::script("ckeditor/plugins/about/dialogs/about.js")}}
{{HTML::script("ckeditor/plugins/clipboard/dialogs/paste.js")}}
{{HTML::script("ckeditor/plugins/dialog/dialogDefinition.js")}}
{{HTML::script("ckeditor/plugins/image/dialogs/image.js")}}
{{HTML::script("ckeditor/plugins/link/dialogs/anchor.js")}}
{{HTML::script("ckeditor/plugins/link/dialogs/link.js")}}
{{HTML::script("ckeditor/plugins/pastefromword/filter/default.js")}}
{{HTML::script("ckeditor/plugins/scayt/dialogs/options.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/specialchar.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/af.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ar.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/bg.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ca.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/cs.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/cy.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/da.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/de.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/el.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/en.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/en-gb.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/eo.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/es.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/et.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/fa.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/fi.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/fr.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/fr-ca.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/gl.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/he.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/hr.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/hu.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/id.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/it.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ja.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/km.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ku.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/lt.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/lv.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/nb.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/nl.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/no.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/pl.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/pt.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/pt-br.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ru.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/si.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/sk.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/sl.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/sq.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/sv.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/th.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/tr.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/tt.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/ug.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/uk.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/vi.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/zh.js")}}
{{HTML::script("ckeditor/plugins/specialchar/dialogs/lang/zh-cn.js")}}
{{HTML::script("ckeditor/plugins/table/dialogs/table.js")}}
{{HTML::script("ckeditor/plugins/tabletools/dialogs/tableCell.js")}}
{{HTML::script("ckeditor/plugins/wsc/dialogs/wsc.js")}}
{{HTML::script("ckeditor/plugins/wsc/dialogs/wsc_ie.js")}}

{{HTML::style("ckeditor/plugins/scayt/dialogs/toolbar.css")}}
{{HTML::style("ckeditor/plugins/wsc/dialogs/wsc.css")}}
